name: flutter_wallet

versioning:
  # Versioning mode, currently only independent supported.
  mode: independent

packages:
  - packages/**
  - app/**
  - embed_app/**

dev_dependencies:
  pedantic: 1.10.0

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks
  # Analyze the project for Dart analysis issues.
  #  - Requires `pub global activate tuneup`.
  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.
  format: pub global run flutter_plugin_tools format

  # Run standard flutter tests in all packages that have them.
  test: >
    melos exec -c 1 --fail-fast --dir-exists=test --ignore="*example*" --ignore="*web*" -- \
      flutter test

  # Coverage
  coverage: >
    melos exec -c 1 --fail-fast --dir-exists=test --ignore="*example*" --ignore="*web*" -- \
      flutter test --coverage

  # Check pubspecs are valid and publishable in each package.
  lint:pub: >
    melos exec -c 5 --fail-fast --no-private --ignore="*example*" -- \
      pub publish --dry-run

  # Clean things very deeply, can be used to establish "pristine checkout" status
  clean:deep: >
    git clean -x -d -f -q

  # Additional cleanup lifecycle script, executed when `melos clean` is ran.
  postclean: >
    melos exec -- \
     rm -rf ./build ./android/.gradle ./ios/.symlinks ./ios/Pods ./android/.idea ./.idea ./.dart-tool/build

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.0"
