name: flutter_ucore
description: A new Flutter boilerplate project.
homepage: http://gitlab.tqxd.com/flutter
publish_to: "none"

# 由此处指定原生包版本, 1.0.0 为appversion, 1 为 build version
version: 1.1.1+2122012501

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Localization https://github.com/dart-lang/intl
  intl: ^0.17.0
  # PDF预览
  # https://pub.flutter-io.cn/packages/advance_pdf_viewer
  advance_pdf_viewer: ^2.0.0
  cupertino_icons: ^1.0.2
  # 获取设备ID
  # https://pub.flutter-io.cn/packages/flutter_device_udid
  flutter_device_udid: ^2.0.0
  # dio cookiejar
  dio_cookie_manager: ^2.0.0
  # 网易易盾
  # https://pub.dev/packages/flutter_net_captcha
  flutter_net_captcha: ^2.0.3
  # 基础kit
  # http://gitlab.tqxd.com/flutter/plugins/flutter_base_kit
  flutter_base_kit:
    # path: /Users/simman/Desktop/flutter_base_kit
    hosted:
      name: flutter_base_kit
      url: https://pub.youzi.dev
    version: 1.2.0
  # action sheet
  flutter_action_sheet:
    hosted:
      name: flutter_action_sheet
      url: https://pub.youzi.dev
    version: ^0.0.1
  # WebView
  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter
  webview_flutter: ^2.0.12
  # 下拉刷新和上拉加载
  # https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^2.0.0
  # 处理键盘
  # https://pub.flutter-io.cn/packages/keyboard_actions
  keyboard_actions: ^3.4.4
  # 启动 URL
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
  url_launcher: ^6.0.9
  # 处理 URL Schemes
  # https://github.com/avioli/uni_links
  uni_links: ^0.5.1
  # sqlite 数据库
  # https://pub.flutter-io.cn/packages/floor
  floor: ^1.1.0
  # 红点
  # https://pub.dev/packages/badges
  badges: ^2.0.1
  # 指示器
  # https://github.com/pyozer/dots_indicator
  dots_indicator: ^2.0.0
  # 选择图片
  #
  fk_photos: ^2.1.0
  # 二维码识别
  r_scan: 0.1.6+1
  # 运行时权限
  # https://pub.flutter-io.cn/packages/permission_handler
  permission_handler: ^8.1.6
  # 更改app icon 角标
  flutter_app_badger: ^1.3.0
  # 爱莫人脸识别
  flutter_aimall_face_recognition:
    hosted:
      name: flutter_aimall_face_recognition
      url: https://pub.youzi.dev
    version: 2.1.6
  # # 图睿OCR
  flutter_turui_ocr:
    hosted:
      name: flutter_turui_ocr
      url: https://pub.youzi.dev
    version: 2.1.0
  flutter_dev_tools:
    hosted:
      name: flutter_dev_tools
      url: https://pub.youzi.dev
    version: ^0.0.1

dependency_overrides:
  yaml: 3.1.0
  camera: ^0.9.4+3

dev_dependencies:
  build_runner: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lint: any
  mockito: any
  test: any
  flutter_launcher_icons: any
  flutter_native_splash: any
  flutter_rename_app_plus: any
  floor_generator: ^1.1.0
  # 国际化语言包翻译自动代码生成工具  使用方法：在Terminal调用flutter pub run i18n_runner
  # http://gitlab.tqxd.com/flutter/plugins/i18n_runner
  i18n_runner:
    version: ^1.1.0+1
    hosted:
      name: i18n_runner
      url: https://pub.youzi.dev




# 更改包名、app名称
# flutter pub run flutter_rename_app_plus
flutter_rename_app_plus:
  application_name: UCore
  dart_package_name: flutter_ucore
  application_id: cn.tqxd.UCoreApp
  bundle_id: io.ucore.app
  android_package_name: cn.tqxd.UCoreApp

# 生成 Icon
#  flutter pub get
#  flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/icons/app_icon_ios.png"
  image_path_android: "assets/icons/app_icon_ad.png"
#  adaptive_icon_background: "assets/icons/adaptive_icon_background.png" # for Android 8.0+ devices
#  adaptive_icon_foreground: "assets/icons/adaptive_icon_foreground.png" # for Android 8.0+ devices

# 生成启动页
# flutter pub run flutter_native_splash:create
# flutter pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#FE9A4E"
  # background_image: "assets/icons/splash.png"
  #image: assets/splash.png
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #android_gravity: center
  #ios_content_mode: center
  android: true
  ios: true
  fullscreen: true

# i18n_runner配置项
# flutter pub run i18n_runner
i18n_runner:
  files:
    # 国际化Json文件
    json: lib/i18n/i18n.json
    # 国际化Keys文件生成
    i18n_keys: lib/generated/i18n_keys.dart
    # 国际化词条文件包名
    translations: lib/i18n/translations/
  locale:
    # 基准语言
    benchmark: zhCN
    # 支持的语言
    supports:
      zhCN: zh_CN
      zhTW: zh_TW
      en: en_US
      ja: ja

# The following section is specific to Flutter.
flutter:
  generate: false
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/pdfs/
    - assets/config/
    - assets/fonts/
    - assets/data/
    - assets/icons/
    - assets/images/
    - assets/images/home/
    - assets/images/common/
    - assets/images/drawer/
    - assets/images/load/
    - assets/images/login/
    - assets/images/news/
    - assets/images/realname/
    - assets/images/rss/
    - assets/images/user/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
