source "https://rubygems.org"
# source "https://gems.ruby-china.com"

gem "fastlane"
gem 'sem_version', '~> 2.0', '>= 2.0.1'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
