name: flutter_wallet
description: A new Flutter boilerplate project.
homepage: http://gitlab.tqxd.com/flutter
publish_to: "none"

# 由此处指定原生包版本, 1.0.0 为appversion, 1 为 build version
version: 2.0.5+2122030104

environment:
  sdk: ">=2.12.0 <3.0.0"

flutter-json:
  enable: true

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Localization https://github.com/dart-lang/intl
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  # 获取设备ID
  # https://pub.flutter-io.cn/packages/flutter_device_udid
  flutter_device_udid: ^2.0.0
  # dio cookiejar
  dio_cookie_manager: ^2.0.0
  # 基础kit
  # http://gitlab.tqxd.com/flutter/plugins/flutter_base_kit
  flutter_base_kit:
    # path: /Users/simman/Desktop/flutter_base_kit
    version: ^1.2.2
    hosted:
      name: flutter_base_kit
      url: https://pub.youzi.dev
  # action sheet
  flutter_action_sheet:
    version: ^0.0.1
    hosted:
      name: flutter_action_sheet
      url: https://pub.youzi.dev
  # WebView
  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter
  webview_flutter: ^2.0.12
  # 下拉刷新和上拉加载
  # https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^2.0.0
  # 列表项侧滑库
  # https://pub.flutter-io.cn/packages/flutter_slidable
  flutter_slidable: ^0.6.0
  # 处理键盘
  # https://pub.flutter-io.cn/packages/keyboard_actions
  keyboard_actions: ^3.4.4
  # 启动 URL
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher/url_launcher
  url_launcher: ^6.0.9
  # 处理 URL Schemes
  # https://github.com/avioli/uni_links
  uni_links: ^0.5.1
  # 红点
  # https://pub.dev/packages/badges
  badges: ^2.0.1
  # 选择图片
  # https://pub.flutter-io.cn/packages/fk_photos
  fk_photos: ^2.1.0
  # Flutter 轮播图
  # https://pub.flutter-io.cn/packages/flutter_carousel_slider
  flutter_carousel_slider: ^1.0.8
  # JSON处理
  json_annotation: ^4.3.0
  decimal: ^1.3.0
  # 本地身份认证（生物识别）
  # http://gitlab.tqxd.com/flutter/plugins/local_auth_plus
  local_auth:
    version: 1.1.8-plus+03
    hosted:
      name: local_auth
      url: https://pub.youzi.dev
  wallet_connect: ^1.0.2
  # 扫码插件
  # http://gitlab.tqxd.com/flutter/plugins/flutter_qrscan_plugin
  flutter_qrscan_plugin:
    version: ^0.2.1
    hosted:
      name: flutter_qrscan_plugin
      url: https://pub.youzi.dev

  # 资源文件模块
  flutter_wallet_assets:
    path: ../packages/flutter_wallet_assets
  # 区块链模块
  flutter_wallet_chain:
    path: ../packages/flutter_wallet_chain
  # dapp 浏览器
  flutter_wallet_dapp_browser:
    path: ../packages/flutter_wallet_dapp_browser
  # 数据库模块
  flutter_wallet_db:
    path: ../packages/flutter_wallet_db

  qr_flutter: ^4.0.0
  flutter_picker: ^2.0.2
  date_format: ^2.0.4
  sqflite_sqlcipher: ^2.1.0

dependency_overrides:
  yaml: 3.1.0
  process_run: ^0.12.2
  permission_handler: 8.1.6
  flutter_svg: ^0.23.0
  camera: 0.9.4+3
  get: 4.3.8

dev_dependencies:
  build_runner: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lint: any
  mockito: any
  test: any
  flutter_launcher_icons: any
  flutter_native_splash: any
  flutter_rename_app_plus: any
  # 国际化语言包翻译自动代码生成工具
  # http://gitlab.tqxd.com/flutter/plugins/i18n_runner
  # flutter pub run i18n_runner
  i18n_runner:
    version: ^1.2.0+1
    hosted:
      name: i18n_runner
      url: https://pub.youzi.dev
  # JSON处理
  # flutter pub run json_partner
  json_serializable: ^6.0.1
  json_partner:
    version: ^2.1.0+1
    hosted:
      name: json_partner
      url: https://pub.youzi.dev
  # IconFontSvg
  # http://gitlab.tqxd.com/flutter/plugins/flutter_iconfont_svg_builder
  # flutter pub run flutter_iconfont_svg_builder
  flutter_iconfont_svg_builder:
    version: ^0.0.5
    hosted:
      name: flutter_iconfont_svg_builder
      url: https://pub.youzi.dev
  # baidu_translator
  # http://gitlab.tqxd.com/flutter/plugins/flutter_baidu_translator_runner
  flutter_baidu_translator_runner:
    version: ^0.0.3
    hosted:
      name: flutter_baidu_translator_runner
      url: https://pub.youzi.dev

# 更改包名、app名称
# flutter pub run flutter_rename_app_plus
flutter_rename_app_plus:
  application_name: AITD Wallet
  application_name_pre: AITD Wallet
  dart_package_name: flutter_wallet
  application_id: io.wallet.app.pre
  bundle_id: io.wallet.app.pre
  android_package_name: com.tianqi.aitdwallet

# 生成 Icon
#  flutter pub get
#  flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  remove_alpha_ios: true
  android: true
  image_path_ios: "assets/icons/app_icon_ios.png"
  image_path_android: "assets/icons/app_icon_ad.png"
  image_path_ios_pre: "assets/icons/app_icon_ios_pre.png"
  image_path_android_pre: "assets/icons/app_icon_ad_pre.png"
#  adaptive_icon_background: "assets/icons/adaptive_icon_background.png" # for Android 8.0+ devices
#  adaptive_icon_foreground: "assets/icons/adaptive_icon_foreground.png" # for Android 8.0+ devices

# 生成启动页
# flutter pub run flutter_native_splash:create
# flutter pub run flutter_native_splash:remove
flutter_native_splash:
  color: "#FFFFFF"
  # background_image: "assets/icons/splash.png"
  #image: assets/splash.png
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #android_gravity: center
  #ios_content_mode: center
  android: true
  ios: true
  fullscreen: true

# i18n_runner配置项
# flutter pub run i18n_runner
i18n_runner:
  files:
    # 国际化Json文件
    json: lib/i18n/i18n.json
    # 国际化Keys文件生成
    i18n_keys: lib/generated/i18n_keys.dart
    # 国际化词条文件包名
    translations: lib/i18n/translations/
  locale:
    # 基准语言
    benchmark: zhCN
    # 支持的语言
    supports:
      zhCN: zh_CN
      zhTW: zh_TW
      en: en_US
      ja: ja
      ko: ko


flutter_iconfont_svg_builder:
  fonts:
    - class-name: IconFont
      dart-file-dir:
      svg-symbol:
        - https://at.alicdn.com/t/font_2905355_yvexpl70dab.js?spm=a313x.7781069.1998910419.73&file=font_2905355_yvexpl70dab.js

# flutter pub run flutter_baidu_translator_runner
flutter_baidu_translator_runner:
  from_path: ./lib/i18n/translator.json
  dest_path: ./lib/i18n/translator.json
  config:
    primary-key: key      # 主键名称, 如设置了 auto-primary-key, 此值必须
    auto-primary-key: 1   # -1 不做任何处理, 0 当值没有时, 并且langs存在en字段, 则自动生成， 1 一律使用langs的en字段进行生成
    case-type: 1          # 1. 驼峰 2. 下划线
    base-key: zhCN        # 基于 xx 进行翻译, 必须
    regen: true           # 如果为true, 则对应语言是否存在值, 都会重新翻译赋值, 非必须
    langs: # 要生成的语言, 支持的语言请查看Readme, 最少设置1个
      kor: ko
      jp: ja
      cht: zhTW
      en: en

# The following section is specific to Flutter.
flutter:
  generate: false
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Din
      fonts:
        - asset: assets/fonts/DIN-BOLD.OTF
