#name: flutter_template
#description: A new Flutter project.
#
#publish_to: 'none' # Remove this line if you wish to publish to pub.dev
#
#version: 1.0.0+1
#
#environment:
#  sdk: ">=2.12.0 <3.0.0"
#
#dependencies:
#  flutter:
#    sdk: flutter
#
#  cupertino_icons: ^1.0.2
#
#dev_dependencies:
#  flutter_test:
#    sdk: flutter
#
#flutter:
#  uses-material-design: true
#


name: flutter_template
description: A new Flutter boilerplate project.
homepage: http://gitlab.tqxd.com/flutter
publish_to: "none"

# 由此处指定原生包版本, 1.0.0 为appversion, 1 为 build version
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Localization https://github.com/dart-lang/intl
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  # 获取设备ID
  # https://pub.flutter-io.cn/packages/flutter_device_udid
  flutter_device_udid: ^2.0.0
  # dio cookiejar
  dio_cookie_manager: ^2.0.0
  # 网易易盾
  # https://pub.dev/packages/flutter_net_captcha
  flutter_net_captcha: ^2.0.2
  # 基础kit
  # http://gitlab.tqxd.com/flutter/plugins/flutter_base_kit
  flutter_base_kit:
    #    path: /Users/simman/Desktop/flutter_base_kit
    hosted:
      name: flutter_base_kit
      url: https://pub.youzi.dev/api/
    version: 1.1.4
  # WebView
  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter/webview_flutter
  webview_flutter: ^2.0.12
  # 上拉加载和下拉刷新
  # https://github.com/peng8350/flutter_pulltorefresh
  pull_to_refresh: ^2.0.0

dependency_overrides:
  yaml: 3.1.0
  get: 4.3.8
  camera: ^0.9.4+14

dev_dependencies:
  build_runner: any
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lint: any
  mockito: any
  test: any
  flutter_launcher_icons: any
  flutter_native_splash: any
  flutter_rename_app: any
  # 国际化语言包翻译自动代码生成工具
  # http://gitlab.tqxd.com/flutter/plugins/i18n_runner
  i18n_runner:
    hosted:
      name: i18n_runner
      url: https://pub.youzi.dev/api/
      version:  ^0.0.3+1

# 更改包名、app名称
# flutter pub run flutter_rename_app
flutter_rename_app:
  application_name: UCore
  dart_package_name: flutter_ucore
  application_id: com.android.bank
  bundle_id: com.ios.bank
  android_package_name: com.bank.app

# 生成 Icon
#  flutter pub get
#  flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icons/app_icon_ios.png"
  image_path_android: "assets/icons/app_icon_ad.png"
#  adaptive_icon_background: "assets/icons/adaptive_icon_background.png" # for Android 8.0+ devices
#  adaptive_icon_foreground: "assets/icons/adaptive_icon_foreground.png" # for Android 8.0+ devices

# 生成启动页
# flutter pub run flutter_native_splash:create
# flutter pub run flutter_native_splash:remove
flutter_native_splash:
  #  color: "#FFFE9A4E"
  background_image: "assets/icons/splash.png"
  #image: assets/splash.png
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #android_gravity: center
  #ios_content_mode: center
  android: true
  ios: true
  fullscreen: true

# The following section is specific to Flutter.
flutter:
  generate: false
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/config/
    - assets/fonts/
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
